We add styles for the admin menu.
BrightCoders-Institute/BCDIC22-RoR-reloj-checador-team3 pull request #17
Opened 2023-01-26 22:33 UTC by DiegoCoronaBarragan

Co-authored-by: AMCernas <elswordmon@gmail.com>
Co-authored-by: M-Cordova-M <alberto971801@gmail.com>

# Description

In this issue, we implemented styles for the admin menu with bootstrap.

## Screenshots

![image](https://user-images.githubusercontent.com/116856441/214965448-77b1c66a-f9fe-44ea-b479-5e7a0dd09ccc.png)

2023-01-26 22:40 UTC, Reiyirak approved these changes
Just add an empty line to the end of the file admin_menu.html.erb

2023-01-26 22:44 UTC, juperameza requested changes

2023-01-26 22:44 UTC, juperameza commented on app/views/admin/admin_menu.html.erb
> -
Add a new line at the end of this file

2023-01-27 02:25 UTC, dagp-ucol approved these changes

2023-01-27 21:38 UTC, juperameza approved these changes
Lgtm

2023-01-27 21:39 UTC, merged