Report view and table to show reports with styles
BrightCoders-Institute/BCDIC22-RoR-reloj-checador-team3 pull request #20
Opened 2023-01-31 23:04 UTC by M-Cordova-M

# Description

What did you implemented/Why did you implemented this:
We added a report view and a table to show the reports, we also made some changes on employee and stores table styles.

## Screenshots

![reloj 5](https://user-images.githubusercontent.com/80138835/215903578-a6b58184-6e36-407d-b218-2be7cbb29f83.PNG)

![reloj 6](https://user-images.githubusercontent.com/80138835/215903595-41420a99-1a95-4079-99be-c4baffdf6b1c.PNG)

2023-02-01 00:07 UTC, Reiyirak approved these changes
Try to remove the development.log, maybe the route is wrong on the gitignore.

2023-02-01 21:54 UTC, MaxRetana approved these changes
LGTM

2023-02-01 22:38 UTC, juperameza requested changes

2023-02-01 22:38 UTC, juperameza commented on app/views/employees/index.html.erb
> +      Register an employee
Standardize your language you have some things in English and some  in Spanish

2023-02-02 16:15 UTC, dagp-ucol approved these changes

2023-02-02 21:55 UTC, juperameza approved these changes
Lgtm

2023-02-02 22:03 UTC, merged