Button Return
BrightCoders-Institute/BCDIC22-RoR-reloj-checador-team3 pull request #22
Opened 2023-02-02 22:14 UTC by DiegoCoronaBarragan

# Description

We implemented a button for returning a previous page in the app if click on the company name, redirecting to the main page.

## Screenshots

![image](https://user-images.githubusercontent.com/116856441/216461074-d70e5720-10af-440a-8631-b625a337e172.png)

2023-02-02 22:33 UTC, JuanequeX requested changes

2023-02-02 22:33 UTC, JuanequeX commented on app/assets/stylesheets/application.css
> +  margin-right: 100px;
sort alphabetically this block

2023-02-02 22:33 UTC, JuanequeX commented on app/assets/stylesheets/application.css
> +.checkin_header a:hover {
add a blank line between this two blocks

2023-02-02 22:33 UTC, JuanequeX commented on app/assets/stylesheets/application.css
> +}
add a blank line between this two blocks, and add a space between your class name an your curly braces

2023-02-03 00:25 UTC, JuanequeX approved these changes

2023-02-03 00:39 UTC, Reiyirak approved these changes
LGTM

2023-02-03 00:40 UTC, Yaxkin121 approved these changes
lgtm

2023-02-03 00:40 UTC, MarcoRodriguez23 approved these changes

2023-02-03 00:41 UTC, merged