reports implemented on the page.
BrightCoders-Institute/BCDIC22-RoR-reloj-checador-team3 pull request #24
Opened 2023-02-03 22:02 UTC by AMCernas

# Description

We implemented the reports section to the projects, we are using the gem chartkick and groupdate to do this, so the reports can be seen as graphics by the users authenticated as admins.

## Screenshots
![image](https://user-images.githubusercontent.com/91897457/216719054-8484f739-579d-497b-8cf7-e52c68cdd0c0.png)

![image](https://user-images.githubusercontent.com/91897457/216719186-a7191610-21aa-42ec-8156-a30e5a4aeece.png)

![image](https://user-images.githubusercontent.com/91897457/216719253-fdd8e35f-3d6d-4bfe-a58f-6f7e88489c12.png)

2023-02-03 22:04 UTC, DiegoMoralesBravo approved these changes

2023-02-03 22:24 UTC, Reiyirak approved these changes

2023-02-04 21:08 UTC, YilKanda requested changes

2023-02-04 21:08 UTC, YilKanda commented on app/assets/stylesheets/application.css
> +
There are unnecessary spaces, which you can remove.

2023-02-04 21:08 UTC, YilKanda commented on app/assets/stylesheets/application.css
> +
There are unnecessary spaces, which you can remove.

2023-02-04 21:08 UTC, YilKanda commented on app/views/reports/generate_report.html.erb
>  </div>
Check the indentation of your file. (Space: 2)

2023-02-04 21:08 UTC, YilKanda commented on config/importmap.rb
> +pin "Chart.bundle", to: "Chart.bundle.js"
Add a blank line.

2023-02-07 22:11 UTC, MarcoRodriguez23 approved these changes
LGFM !!

2023-02-07 23:28 UTC, YilKanda approved these changes
LGTM!

2023-02-07 23:33 UTC, merged