Check-in view created with out functionalities
BrightCoders-Institute/BCDIC22-RoR-reloj-checador-team3 pull request #9
Opened 2023-01-23 23:32 UTC by M-Cordova-M

# Description

We added a check-in view, and tried some styles for the page we also added a clock with date and a form with text fields, it doesnt have functionalities, just styles.

## Screenshots

![reloj 3](https://user-images.githubusercontent.com/80138835/214175639-d825b06e-4820-4458-b701-5706f6f13ffd.PNG)

2023-01-23 23:55 UTC, juperameza approved these changes
Lgtm

2023-01-24 00:34 UTC, MarcoRodriguez23 approved these changes
You can create folders to save your code following the sass 7-1 guide https://sass-guidelin.es/#the-7-1-pattern

2023-01-24 00:57 UTC, dagp-ucol requested changes

2023-01-24 00:57 UTC, dagp-ucol commented on app/assets/stylesheets/application.css
> +    width: 90%;
Alphabetize your CSS

```suggestion
    align-items: center;
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    margin-left: 50px;
    margin-right: 50px;
    padding-bottom: 10px;
    padding-top: 10px;
    width: 90%;
```

2023-01-24 00:57 UTC, dagp-ucol commented on app/assets/stylesheets/application.css
> +
Remove blank line
```suggestion
```

2023-01-24 00:57 UTC, dagp-ucol commented on app/assets/stylesheets/application.css
> +    border-radius: 3px;
Alphabetize your CSS

https://www.linkedin.com/pulse/alphabetize-your-css-get-out-dennis-plucinik/

2023-01-24 00:57 UTC, dagp-ucol commented on app/assets/stylesheets/application.css
> +    height: 140px;
Alphabetize your CSS

https://www.linkedin.com/pulse/alphabetize-your-css-get-out-dennis-plucinik/

2023-01-24 00:57 UTC, dagp-ucol commented on app/assets/stylesheets/application.css
> +    margin-bottom: 35px;
Alphabetize your CSS

https://www.linkedin.com/pulse/alphabetize-your-css-get-out-dennis-plucinik/

2023-01-24 00:57 UTC, dagp-ucol commented on app/assets/stylesheets/application.css
> +    width: 100%;
Alphabetize your CSS

https://www.linkedin.com/pulse/alphabetize-your-css-get-out-dennis-plucinik/

2023-01-24 00:57 UTC, dagp-ucol commented on app/assets/stylesheets/application.css
> +    border-radius: 3px;
Alphabetize your CSS

https://www.linkedin.com/pulse/alphabetize-your-css-get-out-dennis-plucinik/

2023-01-24 01:02 UTC, oscaregr approved these changes
made the nesesary chanfes

2023-01-24 05:38 UTC, dagp-ucol approved these changes

2023-01-24 21:24 UTC, merged